nodes:
<<<<<<< HEAD
  - address: 172.31.65.78
    internal_address: 172.31.65.78
=======
  - address: 172.31.64.97 # ec2 instance public ip address
    internal_address: 172.31.64.97 # ec2 instance private ip address
>>>>>>> feature/msp-26
    user: ubuntu
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/matt-rancher.key

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"